version: '3.8'

# Configurações de ambiente compartilhadas
x-common-env: &common-env
  DATABASE_URL: postgresql://valion_user:valion_password@postgres:5432/valion
  REDIS_URL: redis://redis:6379/0
  CELERY_BROKER_URL: redis://redis:6379/0
  CELERY_RESULT_BACKEND: redis://redis:6379/0
  ENVIRONMENT: production
  LOG_LEVEL: INFO

services:
  # Banco de dados PostgreSQL
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: valion
      POSTGRES_USER: valion_user
      POSTGRES_PASSWORD: valion_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U valion_user -d valion"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Redis para cache e broker Celery
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

  # API FastAPI
  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE_TYPE: api
    ports:
      - "8000:8000"
    environment:
      <<: *common-env
      SERVICE_TYPE: api
    volumes:
      - ./uploads:/app/uploads
      - ./models:/app/models
      - ./reports:/app/reports
      - ./logs:/app/logs
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped

  # Worker Celery
  worker:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE_TYPE: worker
    environment:
      <<: *common-env
      SERVICE_TYPE: worker
    volumes:
      - ./uploads:/app/uploads
      - ./models:/app/models
      - ./reports:/app/reports
      - ./logs:/app/logs
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped

  # Monitor Celery (Flower)
  flower:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE_TYPE: worker
    ports:
      - "5555:5555"
    environment:
      <<: *common-env
    depends_on:
      redis:
        condition: service_healthy
      worker:
        condition: service_started
    restart: unless-stopped
    # Override entrypoint to run flower directly instead of using docker-entrypoint.sh
    entrypoint: ["celery", "-A", "src.workers.tasks", "flower", "--port=5555"]

  # Frontend Streamlit
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE_TYPE: frontend
    ports:
      - "8501:8501"
    environment:
      API_BASE_URL: http://api:8000
      WS_BASE_URL: ws://api:8000
      STREAMLIT_SERVER_PORT: 8501
      STREAMLIT_SERVER_ADDRESS: 0.0.0.0
      SERVICE_TYPE: frontend
    depends_on:
      api:
        condition: service_healthy
    restart: unless-stopped

  # Nginx para proxy reverso (opcional)
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/ssl:ro
    depends_on:
      - api
      - frontend
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:

networks:
  default:
    name: valion_network